clone:
  recursive: true
  submodule_override:
    themes/blackburn: https://github.com/yoshiharuyamashita/blackburn.git

build:
  image: golang:alpine
  commands:
    - apk add --no-cache git nodejs curl
    - go get -v github.com/spf13/hugo
    - npm install hugo-lunr
    - hugo --theme blackburn
    - npm run index

deploy:
  rsync:
    user: deploy
    host: lon1.internal.trozzy.xyz
    port: 22
    source: public
    target: /opt/web/trozzy.net/
    delete: true
    recursive: true
  rsync:
    user: deploy
    host: lon2.internal.trozzy.xyz
    port: 22
    source: public
    target: /opt/web/trozzy.net/
    delete: true
    recursive: true
  rsync:
    user: deploy
    host: lon3.internal.trozzy.xyz
    port: 22
    source: public
    target: /opt/web/trozzy.net/
    delete: true
    recursive: true
  rsync:
    user: deploy
    host: lon4.internal.trozzy.xyz
    port: 22
    source: public
    target: /opt/web/trozzy.net/
    delete: true
    recursive: true
