baseurl = "https://www.trozzy.net/"
title = "Just another blog"
author = "Trozz"
# Shown in the side menu
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A brain dump of Trozz"
  brand = "TrozzY"
  googleAnalytics = "UA-39926379-1"
  # disqus = "trozz"
  # CSS name for highlight.js
  highlightjs = "agate"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    url = "/contact/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "trozz"
  facebook = "trozz1548"
  googleplus = "+MichaelLeer"

  # SNS photo/video sharing
  youtube = "trozz"

  # SNS career oriented
  linkedin = "trozz"

  # SNS news
  reddit = "trozz1548"

  # Techie
  github = "Trozz"
  bitbucket = "Trozz"
  stackoverflow = "989652/trozz"
  serverfault = "55793/trozz"


  # Other
  keybase = "trozz"
